version: "3.7"
services:
  
  security-service:
    image: springmicroservice360/security-service:0.0.1-SNAPSHOT
    environment:
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_SERVER_HOST_PEER1=eureka-peer1
      - EUREKA_SERVER_HOST_PEER2=eureka-peer2
    ports:
      - "9898:9898"
    restart: always
    depends_on: # Start the depends_on first
      - config-server
      - eureka-peer1
      - eureka-peer2
    networks:
      - ecommerce-network
      
  eureka-peer1:
    image: springmicroservice360/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-peer1
    environment:
      - SPRING_PROFILES_ACTIVE=peer1
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_SERVER_HOST_PEER1=eureka-peer1
      - EUREKA_SERVER_HOST_PEER2=eureka-peer2
    ports:
      - "8761:8761"
    restart: always
    depends_on: # Start the depends_on first
      - config-server
    networks:
      - ecommerce-network

  eureka-peer2:
    image: springmicroservice360/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-peer2
    environment:
      - SPRING_PROFILES_ACTIVE=peer2
      - CONFIG_SERVER_HOST=config-server
      - EUREKA_SERVER_HOST_PEER1=eureka-peer1
      - EUREKA_SERVER_HOST_PEER2=eureka-peer2
    ports:
      - "8762:8762"
    restart: always
    depends_on: # Start the depends_on first
      - config-server
    networks:
      - ecommerce-network

  config-server:
    image: springmicroservice360/config-server:0.0.1-SNAPSHOT
    ports:
      - "5000:5000"
    restart: always
    container_name: config-server
    networks:
      - ecommerce-network

# Networks to be created to facilitate communication between containers
networks:
  ecommerce-network:
